version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: challenge_logixs
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/auth_db
      JWT_SECRET: your_jwt_secret_key_here
      JWT_EXPIRES_IN: 24h
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
