services:
  - type: web
    name: challenge-logixs-api
    env: node
    buildCommand: npm install && npx nx build api
    startCommand: npx nx serve api:production
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: challenge_logixs_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: challenge_logixs_db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: challenge_logixs_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: challenge_logixs_db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: challenge_logixs_db
          property: database
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h

databases:
  - name: challenge_logixs_db
    databaseName: challenge_logixs
    user: challenge_logixs 